services:
  - type: web
    name: supportdesk
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false